# Generated by Django 5.1.3 on 2025-07-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_tasks_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
